# Generated by Django 2.0.1 on 2018-01-28 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.CharField(choices=[('ACCT', 'ACCT - Accounting'), ('ACTS', 'ACTS - Actuarial Science'), ('AHST', 'AHST - Art History'), ('AMS', 'AMS - American Studies'), ('AP', 'AP - Art and Performance'), ('ARAB', 'ARAB - Arabic'), ('ARHM', 'ARHM - Arts and Humanities'), ('ARTS', 'ARTS - Art'), ('ATCM', 'ATCM - Arts Tech and Comm'), ('ATEC', 'ATEC - Arts and Tech'), ('ATEM', 'ATEM - Arts Tech and Emmerging Comm'), ('AUD', 'AUD - Audiology'), ('BA', 'BA - Business Admin'), ('BCOM', 'BCOM - Business Comm'), ('BIOL', 'BIOL - Biology'), ('BIS', 'BIS - Interdisciplinary Studies'), ('BLAW', 'BLAW - Business Law'), ('BMEN', 'BMEN - Biomedical Engineering'), ('BPS', 'BPS - Business Policy and Strategy'), ('CE', 'CE - Computer Engineering'), ('CGS', 'CGS - Cognitive Science'), ('CHEM', 'CHEM - Chemistry'), ('CHIN', 'CHIN - Chinese'), ('CLDP', 'CLDP - Child Learning and Development'), ('COMM', 'COMM - Communications'), ('CRIM', 'CRIM - Criminology'), ('CRWT', 'CRWT - Creative Writing'), ('CS', 'CS - Computer Science'), ('DANC', 'DANC - Dance'), ('ECON', 'ECON - Economics'), ('ECS', 'ECS - Engineering and Computer Science'), ('ECSC', 'ECSC - Engineering and Computer Science COOP'), ('ED', 'ED - Education'), ('EE', 'EE - Electrical Engineering'), ('EMAC', 'EMAC - Emmerging Media and Communications'), ('ENGR', 'ENGR - Engineering'), ('ENGY', 'ENGY - Energy Management'), ('ENTP', 'ENTP - Innovation and Entrepeneurship'), ('ENVR', 'ENVR - Environmental Science'), ('EPPS', 'EPPS - Economic, Political, and Policy Sciences'), ('FILM', 'FILM - Film Studies'), ('FIN', 'FIN - Finance'), ('FREN', 'FREN - French'), ('GEOG', 'GEOG - Geography'), ('GEOS', 'GEOS - Geosciences'), ('GERM', 'GERM - German'), ('GISC', 'GISC - Geospatial Information Sciences'), ('GOVT', 'GOVT - Government'), ('GST', 'GST - Gender Studies'), ('HIST', 'HIST - History'), ('HLTH', ' HLTH - Health Care Studies'), ('HMGT', 'HMGT - Healthcare Management'), ('HONS', 'HONS - Honors College'), ('HUMA', 'HUMA - Humanities'), ('IMS', 'IMS - International Management Studies'), ('IPEC', 'IPEC - International Political Economy'), ('ISAE', 'ISAE - Interdisciplinary Studies - Arts Tech and Emmerging Comm'), ('ISAH', 'ISAH - Interdisciplinary Studies - Arts and Humanities'), ('ISEC', 'ISEC - Interdisciplinary Studies - Electrical Engineering and Computer Science'), ('ISIS', 'ISIS - Interdisciplinary Studies'), ('ISNS', 'ISNS - Interdisciplinary Studies - Natural Science and Mathematics'), ('ISSS', 'ISSS - Interdisciplinary Studies - Social Science'), ('ITSS', 'ITSS - Information Technologies and Systems'), ('JAPN', 'JAPN - Japanese'), ('LANG', 'LANG - Language'), ('LIT', 'LIT - Literary Studies'), ('MATH', 'MATH - Mathematical Science'), ('MECH', 'MECH - Mechanical Engineering'), ('MECO', 'MECO - Managerial Economics'), ('MKT', 'MKT - Marketing Management'), ('MUSI', 'MUSI - Music'), ('NANO', 'NANO - Nanoscience'), ('NATS', 'NATS - Natural Sciences'), ('NSC', 'NSC - Neuroscience'), ('OBHR', 'OBHR - Organizational Behaviour/Human Resources'), ('OPRE', 'OPRE - Operations Research'), ('PA', 'PA - Public Affairs Management'), ('PHIL', 'PHIL - Philosophy'), ('PHIN', 'PHIN - Physical Instruction'), ('PHYS', 'PHYS - Physics'), ('PPOL', 'PPOL - Public Policy'), ('PSCI', 'PSCI - Political Science'), ('PSY', 'PSY - Psychology'), ('REAL', 'REAL - Real Estate'), ('RHET', 'RHET - Rhetoric'), ('RMIS', 'RMIS - Risk Management and Insurance'), ('SE', 'SE - Software Engineering'), ('SOC', 'SOC - Sociology'), ('SOCS', 'SOCS - Social Sciences'), ('SPAN', 'SPAN - Spanish'), ('SPAW', 'SPAW - Speech - Language Pathology and Audiology'), ('STAT', 'STAT - Statistics'), ('TE', 'TE - Telecommunications Engineering'), ('THEA', 'THEA - Theatre'), ('UNIV', 'UNIV - University Course'), ('DMTH', 'DMTH - Developmental Math'), ('DRDG', 'DRDG - Developmental Reading'), ('DWTG', 'DWTG - Developmental Writing')], default='ACCT', max_length=4, verbose_name='Subject')),
                ('class_num', models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Invalid input')], verbose_name='Class number')),
                ('coreq', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Co-requisite+', to='courseData.Course')),
                ('prereq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pre-requisite+', to='courseData.Course')),
            ],
        ),
    ]
